---
name: Release Pipeline

"on":
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

env:
  FPM_VERSION: 1.15.1

jobs:
  versions:
    name: Get Version Data
    runs-on: ubuntu-latest
    steps:
      - name: Restic
        id: restic
        uses: pozetroninc/github-action-get-latest-release@53d33d213ee71c72360e3c829caf7cee94ec21e2
        with:
          owner: restic
          repo: restic
          excludes: prerelease, draft
      - name: Checkout
        uses: actions/checkout@v4
      - name: Last Build
        id: last_build
        run: echo "last_version=$(cat LATEST-VERSION)" >> "$GITHUB_OUTPUT"
    outputs:
      restic_version: ${{ steps.restic.outputs.release }}
      last_version: ${{ steps.last_build.outputs.last_version }}

  packages:
    name: Debian Packages
    needs: versions
    if: needs.versions.outputs.restic_version != needs.versions.outputs.last_version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Restic Binaries
        shell: bash
        run: |
          VERSION_TAG="${{ needs.versions.outputs.restic_version }}"
          VERSION_NO_V="${VERSION_TAG:1}"
          mkdir -p ./src
          pushd ./src
          wget -q "https://github.com/restic/restic/releases/download/${VERSION_TAG}/restic_${VERSION_NO_V}_linux_386.bz2"
          wget -q "https://github.com/restic/restic/releases/download/${VERSION_TAG}/restic_${VERSION_NO_V}_linux_amd64.bz2"
          wget -q "https://github.com/restic/restic/releases/download/${VERSION_TAG}/restic_${VERSION_NO_V}_linux_arm.bz2"
          wget -q "https://github.com/restic/restic/releases/download/${VERSION_TAG}/restic_${VERSION_NO_V}_linux_arm64.bz2"
          bunzip2 -- *.bz2
          ls -lh
          popd

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Ruby version
        run: ruby --version
      - name: Install fpm
        run: |
          gem install --no-document fpm -v "$FPM_VERSION"

      - name: Build packages
        shell: bash
        run: |
          VERSION_TAG="${{ needs.versions.outputs.restic_version }}"
          VERSION_NO_V="${VERSION_TAG:1}"
          mkdir -p ./out
          chmod 0555 ./src/restic_*
          fpm -t deb -v ${VERSION_NO_V} -p ./out/restic-${VERSION_NO_V}-amd64.deb -a amd64 ./src/restic_${VERSION_NO_V}_linux_amd64=/usr/bin/restic
          fpm -t deb -v ${VERSION_NO_V} -p ./out/restic-${VERSION_NO_V}-i386.deb -a i386 ./src/restic_${VERSION_NO_V}_linux_386=/usr/bin/restic
          fpm -t deb -v ${VERSION_NO_V} -p ./out/restic-${VERSION_NO_V}-arm64.deb -a arm64 ./src/restic_${VERSION_NO_V}_linux_arm64=/usr/bin/restic
          fpm -t deb -v ${VERSION_NO_V} -p ./out/restic-${VERSION_NO_V}-armhf.deb -a armhf ./src/restic_${VERSION_NO_V}_linux_arm=/usr/bin/restic
          ls -lh ./out

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: Packages
          path: out/*.deb

      - name: Update LATEST-VERSION
        shell: bash
        run: |
          echo "${{ needs.versions.outputs.restic_version }}" > ./LATEST-VERSION

      - name: Commit LATEST-VERSION
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5
        with:
          add: "LATEST-VERSION"
          author_name: cdzombak-3p-release-bot
          author_email: cdzombak-3p-release-bot@users.noreply.github.com
          message: Update LATEST-VERSION to ${{ needs.versions.outputs.restic_version }}
          pathspec_error_handling: exitImmediately
          push: true
          tag: "${{ needs.versions.outputs.restic_version }}"

  release:
    name: GitHub Release
    needs: [packages, versions]
    runs-on: ubuntu-latest
    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: out
      - name: List artifacts
        working-directory: out
        run: ls -R

      - name: Create GitHub release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda
        with:
          files: out/*.deb
          prerelease: false
          fail_on_unmatched_files: true
          generate_release_notes: false
          tag_name: "${{ needs.versions.outputs.restic_version }}"

  aptly:
    name: Aptly
    needs: [versions, packages]
    runs-on: ubuntu-latest
    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: out
      - name: List artifacts
        run: ls -R
        working-directory: out

      - name: Login to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:github-actions

      - name: Push to Aptly Repo
        shell: bash
        run: |
          set -x
          for DEB in out/*.deb; do
            curl -u "${{ secrets.APTLY_CRED }}" \
              -fsS -X POST \
              -F file=@"${DEB}" \
              "${{ secrets.APTLY_API }}/files/restic-${{ needs.versions.outputs.restic_version }}"
          done
          curl -u "${{ secrets.APTLY_CRED }}" \
            -fsS -X POST \
            "${{ secrets.APTLY_API }}/repos/3p/file/restic-${{ needs.versions.outputs.restic_version }}?forceReplace=1"

      - name: Update Published Aptly Repo
        run: |
          set -x
          curl -u "${{ secrets.APTLY_CRED }}" \
            -fsS -X PUT \
            -H 'Content-Type: application/json' \
            --data '{"ForceOverwrite": true}' \
            "${{ secrets.APTLY_API }}/publish/s3:dist.cdzombak.net:deb_3p/any?_async=true"
